### ISSUE TITLE
Not compatible with UE 5.6

### ISSUE THREAD

**Issue by Dima-Digital** [luyuancpp/ue5-export-nav-data#1]
Unfortunately, I can't get it to work on UE 5.6.
I think the Recast API has changed in 5.6.

Unfortunately, my C++ skills are not sufficient to fix this myself.

I would really appreciate some help.

Warnings:
'ARecastNavMesh::CellHeight': Use NavMeshResolutionParams to set CellHeight for the different resolutions instead - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
'ARecastNavMesh::CellHeight': Use NavMeshResolutionParams to set CellHeight for the different resolutions instead - Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.

Errors:
'UE::Core::Private::FormatStringSan::TCheckedFormatStringPrivate<FString::FmtCharType,int>::TCheckedFormatStringPrivate': call to immediate function is not a constant expression
'type cast': cannot convert from 'const rcBorderSize' to 'int'
'UE::Core::Private::FormatStringSan::TCheckedFormatStringPrivate<FString::FmtCharType>::TCheckedFormatStringPrivate': call to immediate function is not a constant expression
'FGenericPlatformMath::Sqrt': ambiguous call to overloaded function
'FGenericPlatformMath::Sqrt': ambiguous call to overloaded function
'PolyMaxHeight': is not a member of 'FRecastBuildConfig'
'UE::Core::Private::FormatStringSan::TCheckedFormatStringPrivate<FString::FmtCharType>::TCheckedFormatStringPrivate': call to immediate function is not a constant expression
static function 'bool UE4RecastHelper::GetRandomPointInRadius(dtNavMeshQuery *,dtQueryFilter *,const UE4RecastHelper::FVector3 &,const UE4RecastHelper::FVector3 &,UE4RecastHelper::FVector3 &)' declared but not defined
The command "D:\UnrealEngine\UE_5.6\Engine\Build\BatchFiles\Build.bat MMOEditor Win64 Development -Project="D:\UnrealEngine\Projects\MMO\MMO.uproject" -WaitMutex -FromMsBuild -architecture=x64" exited with code 6.
